CREATE TABLE Room(
  Room_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  Name VARCHAR(16) NOT NULL,
  Room_number CHAR(16) NOT NULL UNIQUE,
  Bed_info VARCHAR(16) NOT NULL,
  Air_conditioning BOOLEAN,
  Price VARCHAR(16) NOT NULL
);

CREATE TABLE Guest(
  Guest_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  First_name VARCHAR(64),
  Last_name VARCHAR(64),
  Email_address VARCHAR(64),
  Nationality VARCHAR(12),
  Phone_number VARCHAR(24)
);

CREATE TABLE Reservation(
  RESERVATION_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
  Room_id BIGINT NOT NULL,
  Guest_id BIGINT NOT NULL,
  RES_DATE DATE
);

ALTER TABLE Reservation ADD FOREIGN KEY (Room_id) REFERENCES Room(Room_id);
ALTER TABLE Reservation ADD FOREIGN KEY (Guest_id) REFERENCES GUEST(Guest_id);
CREATE INDEX IDX_RES_DATE_ ON RESERVATION(RES_DATE);
